### PR TITLE
Make Modelica FMUs for Spawn portable

### LINKED ISSUE #2443: ModelicaBuildingsEnergyPlus FMU in Dymola lacks spawn binary in windows
When I export the model `Buildings.ThermalZones.EnergyPlus.Examples.SmallOffice.Guideline36Summer` as a FMU from Dymola and simulate in PYFMI, the following errors pop out during initialization:

```txt
FMIL: module = Model, log level = 2: [][FMU status:Error] Error: The following error was detected at time: 17366400
FMIL: module = Model, log level = 2: [][FMU status:Error] Executable c:/users/yangyang.fu/appdata/local/temp/JModelica.org/jm_tmpz6wkk6/resources/legal.html/Resources/bin/spawn-win64/bin/spawn.exe' does not exist: 'No such file or directory'.
FMIL: module = Model, log level = 2: [][FMU status:Error] The stack of functions is:
FMIL: module = Model, log level = 2: [][FMU status:Error] Buildings.ThermalZones.EnergyPlus.BaseClasses.initialize
FMIL: module = Model, log level = 2: [][FMU status:Error] Buildings.ThermalZones.EnergyPlus.BaseClasses.initialize(
flo.wes.fmuZon.adapter, 
flo.building.isSynchronized)
FMIL: module = Model, log level = 2: [][FMU status:Error] fmiInitialize: dsblock_ failed, QiErr = 1
FMIL: module = Model, log level = 2: [][FMU status:Error] Unless otherwise indicated by error messages, possible errors are (non-exhaustive):
The model references external data that is not present on the target machine, at least not with the same location.
```

Apparently the `spawn.exe` binary is not packaged with the generated FMU. So I'm wondering if this is a developing feature or I made a mistake in the previous process. 

The following bash codes are used to generate the errors in my computer:
```bash
  rem add library dependencies
  rem add Buildings library to Modelicapath
  echo on
  set BUILDINGS_PATH="D:\github\modelica-buildings"
  set MODELICAPATH=%BUILDINGS_PATH%;%MODELICAPATH%
  rem add spawn binary to system path
  set SPAWN_PATH="D:\github\modelica-buildings\Buildings\Resources\bin\spawn-win64\bin"
  set PATH=%SPAWN_PATH%;%PATH%
  rem run dymola to generate ModelicaEnergyPlus(FMU)
  dymola -nowindow Guideline36Summer.mos
  rem call Modelica fmu in pyfmi
  python test_g36.py
```

The Modelica script `Guideline36Summer.mos` is:
```modelica
translateModelFMU("Buildings.ThermalZones.EnergyPlus.Examples.SmallOffice.Guideline36Summer", 
    false, 
    "Guideline36Summer", 
    "2", 
    "cs", 
    false, 
    1);
exit();
```

and the Python script `test_g36.py` is
```python
  from pyfmi import load_fmu
  g36 = load_fmu('Guideline36Summer.fmu')
  # simulation
  res = g36.simulate(start_time=201*24*3600., final_time=202.*24*3600)
  # get results
  print res["time"]
  print res["flo.cor.TAir"]
```

### PR DESCRIPTION
**Pull request by mwetter**
This closes https://github.com/lbl-srg/modelica-buildings/issues/2054
This closes #2443

It also adds a tests that checks whether the generated FMU can be moved to another part of the file system.

### CODE REVIEW

File: Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/BuildingInstantiate.c [hunk 1]
```diff
@@ -640,8 +652,33 @@ void generateAndInstantiateBuilding(FMUBuilding* bui){
         bui->time, bui->modelicaNameBuilding, bui->precompiledFMUAbsPat, bui->fmuAbsPat);
     copyBinaryFile(bui->precompiledFMUAbsPat, bui->fmuAbsPat, SpawnFormatError);
   }
-  else
-    generateFMU(bui, modelicaBuildingsJsonFile);
+  else{
+    /* Try to generate FMU with absolute path */
+#ifdef _WIN32 /* Win32 or Win64 */
```
Comment (kbenne) [inline Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/BuildingInstantiate.c:657]: @mwetter I think there needs to be an addition, where spawn2 is the instance of Spawn located by the environment variable SPAWNPATH, and then spawn3 becomes what you now have as spawn2, which is the instance of Spawn on the system path.

You have captured this on the architecture page https://lbl-srg.github.io/soep/softwareArchitecture.html#distribution-of-spawn-and-the-modelica-buildings-library, including SPAWNPATH at my request, however I think this PR was generated before we discussed the SPAWNPATH addition. Can you make a code revision that accounts for all three levels of the spawn search?

Comment (mwetter) [reply Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/BuildingInstantiate.c:657]: @kbenne : That is on my to-do list. This code change was indeed before the architecture page was updated.

Comment (mwetter) [reply Buildings/Resources/src/ThermalZones/EnergyPlus/C-Sources/BuildingInstantiate.c]: This will be done through https://github.com/lbl-srg/modelica-buildings/issues/2759
